name: "CD"

on:
  release:
    types: [published]
env:
  CARGO_TERM_COLOR: always
concurrency: 
  group: 'cd'
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-slim
    timeout-minutes: 30
    environment: CD
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Cargo publish
        continue-on-error: true
        env:
          CRATES_IO_API_TOKEN: ${{ steps.auth.outputs.token }}
        run: |-
          for crate in ascii-img2 ascii-img2-cli; do
            cargo publish -p $crate
          done
